### ISSUE TITLE
Randomizer is returning nothing?

### ISSUE THREAD

**Issue by fixator10** [mrpotatofactory/youtube-load#2]
Just downloaded and put on webserver, then put API key.

An i doing something wrong?
![2016-05-08 16-24-47](https://cloud.githubusercontent.com/assets/11073934/15097814/12bc7c96-153a-11e6-8353-1f1284952e8c.png)
(Here also an space (bug?) under bottom panel)
![2016-05-08 16-25-10](https://cloud.githubusercontent.com/assets/11073934/15097811/12bc1e36-153a-11e6-8205-ac8fe49663fd.png)
![2016-05-08 16-26-11](https://cloud.githubusercontent.com/assets/11073934/15097813/12bc0c52-153a-11e6-8a9d-d8cafc9f90ed.png)
![2016-05-08 16-26-34](https://cloud.githubusercontent.com/assets/11073934/15097816/12c14ece-153a-11e6-8397-a4bbad4f63cb.png)
![2016-05-08 16-26-54](https://cloud.githubusercontent.com/assets/11073934/15097812/12bc2ec6-153a-11e6-9582-16a13c99368f.png)
![2016-05-08 16-27-07](https://cloud.githubusercontent.com/assets/11073934/15097815/12be3a36-153a-11e6-8631-4e40df6568df.png)

**Comment by moonexpr** [comment]
I believe that I fixed this before on mine.
I'll release a patch sometime later along with updating the pococraft
branch with our latest design.
